services:
  greengrass:
    build:
      context: .
    container_name: greengrass
    volumes:
      - ./config:/greengrass/v2/config
      - ./deployments:/greengrass/v2/deployments
      - ./logs:/greengrass/v2/logs
      - ./certs:/greengrass/v2/certs
    environment:
      - SVCUID=0
      - AWS_REGION=${AWS_REGION}
